### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by iKhilya** [MCMrARM/mcpe-json-editor#2]
Hello. Can you please compile this application and lay out the exe file?

**Comment by MCMrARM** [comment]
Hello,
This tool is far from completion and is probably sadly useless with newer MCPE releases.

It's basically a dropped project and is not really useful as I said.

**Comment by MCMrARM** [comment]
As for compilation, use Qt Creator, but unless you're willing to take over it doesn't make much sense to build it.

**Comment by iKhilya** [comment]
Dobrogo vremeni sutok. A chto posovetuyete iz programm dlya izmeneniya interfeysa? YA ispol'zuyu versiyu MCPE 1.0.4.11. Budet-li sozdano novoye prilozheniye ili zhe obnovitsya eto? I eta programma izmenyat' interfeys do versii 0.14.3? Izvinite za moy plokhoy angliyskiy, vo vsem vinvovat Google perevodchik)) Spasibo.
Развернуть
 
302/5000
 
 
Good day. And what advise from the program to change the interface? I am using MCPE version 1.0.4.11.
Will a new application be created or will it be updated? And this program to change the interface to version 0.14.3? Sorry for my bad English, Google translator in all crap)) Thank you.


>Воскресенье, 24 марта 2019, 17:45 +03:00 от MCMrARM <notifications@github.com>:
>
>As for compilation, use Qt Creator, but unless you're willing to take over it doesn't make much sense to build it.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
iKhilya

**Comment by iKhilya** [comment]
Good day. And what advise from the program to change the interface? I am using MCPE version 1.0.4.11.
Will a new application be created or will it be updated? And this program to change the interface to version 0.14.3? Sorry for my bad English, Google translator in all crap)) Thank you.


>Воскресенье, 24 марта 2019, 17:45 +03:00 от MCMrARM <notifications@github.com>:
>
>As for compilation, use Qt Creator, but unless you're willing to take over it doesn't make much sense to build it.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
iKhilya
